First try lesson 12
eugene-okulik/Razmik pull request #12
Opened 2024-02-17 04:37 UTC by RazmikGrygoryan

Думаю будет много попыток сделать это дз)))

2024-02-18 07:59 UTC, eugene-okulik requested changes
Кроме того, что в коментах, не хватает еще методов для сортировки цветов в букете. Т.е. цветы в букет то добавляются как попало, но нужно сделать такие методы, с помощью которых можно будет отсортировать цветы, например по длине стебля. И тогда в списке цветов цветы будут располагаться по возрастанию длины их стебля.

2024-02-18 07:59 UTC, eugene-okulik commented on homework/razmik_gyrgoryan/lesson_12/task_1.py
> +        return self if self.svejest or self.color or self.len_steble or self.price or self.life_time else None
А как найти цветок с помощью этого метода? Вот я хочу найти желтый цветок. Как мне это сделать с помощью этого метода?

2024-02-18 07:59 UTC, eugene-okulik commented on homework/razmik_gyrgoryan/lesson_12/task_1.py
> +        super().__init__(svejest, color, len_steble, price, life_time)
Если в родительском классе кроме всех атрибутов добавить еще, например `title`, то можно было бы каждый класс не делать копией родительского. А, например, для объектов этого класса сразу заполнять этот `title`  
То есть родительский был бы так
```python
class Flowers:
    def __init__(self, title, svejest, color, len_steble, price, life_time):
```
а дочерний так
```python
class Roses(Flowers):
    def __init__(self, svejest, color, len_steble, price, life_time):
        super().__init__(svejest, 'Rose', color, len_steble, price, life_time)
```

2024-02-19 12:04 UTC, RazmikGrygoryan commented
done

2024-02-19 20:18 UTC, eugene-okulik requested changes

2024-02-19 20:18 UTC, eugene-okulik commented on homework/razmik_gyrgoryan/lesson_12/task_1.py
> +        super().__init__(svejest, "Tulip", color, len_steble, price, life_time)
Родительский класс в методе `__init__` первым параметром принимает title, а ты ему туда свежесть передаешь.

2024-02-19 20:18 UTC, eugene-okulik commented on homework/razmik_gyrgoryan/lesson_12/task_1.py
> +        return sorted(self.flowers.svejest)
Здесь ты обращаешься к списку и пытаешься из него взять svejest, но в списке нет такого. Такое есть только у элементов списка.  
Сортировка элементов по свежести будет выглядеть так:
```python
def sort_svejest(self):
    return sorted(self.flowers, key=lambda x: x.svejest)
```

2024-02-20 02:05 UTC, RazmikGrygoryan commented
Исправил)

2024-02-20 08:17 UTC, eugene-okulik approved these changes

2024-02-20 08:17 UTC, merged