first try python project
eugene-okulik/Razmik pull request #17
Opened 2024-02-29 05:27 UTC by RazmikGrygoryan

Написал я что-то не понятное))

2024-02-29 07:43 UTC, eugene-okulik requested changes
Сдавай программу только если она у тебя запускается. Если что-то не понятно или не получается, пиши.  
Пока что всё, что сделано не похоже на то, что написано в требованиях.

2024-02-29 07:43 UTC, eugene-okulik commented on homework/razmik_gyrgoryan/python_project/task.py
> +        date = datetime.strptime(i[:23], date_format)
ВОт эта строка не работает, так как в самом модуле datetime нет такой функции как strptime, такая функция есть в модуле datetime.datetime

2024-02-29 07:43 UTC, eugene-okulik commented on homework/razmik_gyrgoryan/python_project/task.py
> +        date = datetime.strptime(i[:23], date_format)
Этот код, когда напишешь правильно, будет падать, так как не каждая строка логов начинается с даты

2024-03-03 13:49 UTC, RazmikGrygoryan commented
Теперь вроде бы done

2024-03-04 06:21 UTC, eugene-okulik approved these changes

2024-03-04 06:21 UTC, merged