Completed lesson 8
eugene-okulik/Razmik pull request #8
Opened 2024-02-09 17:48 UTC by RazmikGrygoryan

2024-02-10 07:33 UTC, eugene-okulik requested changes

2024-02-10 07:33 UTC, eugene-okulik commented on homework/razmik_gyrgoryan/lesson_8/task_2.py
> +list_fibonaci = list(fib_rec(100000))
Идея генераторов в том, чтобы избавиться от необходимости хранить огромные данные в одной переменной. А здесь ты сделал генератор, позволив это, но потом результат превратил в список и в итоге огромный массив данных поместил в одну переменную.  
Более того, последовательность фибоначчи - бесконечная, но ты реализовал ее не бесконечной. А если бы ты реализовал ее правильно, то превратить ее результат в список у тебя бы не получилось, потому что бесконечных списков не бывает.  
Нужно решить это так, чтобы не превращать результат генератора в список.

2024-02-10 16:52 UTC, RazmikGrygoryan commented
Исправил, вроде0))

2024-02-11 07:38 UTC, eugene-okulik requested changes
Отлично. Осталась одна проблема - твоя программа никогда не останавливается и работает вечно.

2024-02-11 15:55 UTC, RazmikGrygoryan commented
Теперь и не бесконечный)

2024-02-12 10:24 UTC, eugene-okulik approved these changes

2024-02-12 10:24 UTC, merged